MathJax.Hub.Config({
	jax: ["input/TeX", "output/CommonHTML"],
	TeX: {
		TagSide: "right",
		TagIndent: ".8em",
		equationNumbers: {
			autoNumber: "AMS"
		},
		Macros: {
			R: '{\\mathbb R}',
			N: '{\\mathbb N}',
			C: '{\\mathbb C}',
			P: '{\\mathbb P}',
			p: '{\\partial}',
			d: '{\\text d}',
			n: '{\\nabla}',
			T: '{\\mathbb T}',
			vecttwo: ['\\left|\\begin{array}{c}{#1}\\\\#2\\end{array}\\right.', 2],
			vectthree: ['\\left|\\begin{array}{c}{#1}\\\\#2\\\\#3\\end{array}\\right.', 3],
			arccosh: '{\\text arccosh}',
			arcsinh: '{\\text arcsinh}',
			arctanh: '{\\text arctanh}',
			boldx: '{\\mathbf x}',
		    boldxi: '{\\boldsymbol \\xi}',
			bR: '{\\mathbf R}',
			bP: '{\\mathbf P}',
			bZ: '{\\mathbf Z}',
			bC: '{\\mathbf C}',
			VS: '{\\mathbf{R}^2}',
			SVS: '{\\underline V}',
			SO: '{\\mathbf SO}',
			Sym: '{\\mathbf Sym}',
			qi: '{\\mathbf i}',
			qj: '{\\mathbf j}',
			qk: '{\\mathbf k}',
			ec: '{\\hat{\\mathbf e}}',
			xc: '{\\hat{\\mathbf x}}',
			strain: '{\\underline \\epsilon}',
			stress: '{\\underline \\sigma}',
			strainrate: '{\\underline \\epsilon^.}',
			stressrate: '{\\underline \\sigma^.}',
			stiff: '{\\; \\underline{\\underline C}\\;}',
			comply: '{\\underline{\\underline \\kappa}\\;}',
			Id: '{\\mathbf I}',
			Div: '{\\nabla \\cdot}',
			Grad: '{\\mathbf{\\nabla}}',
			rot: '{\\nabla \\times}',
			lap: '{\\triangle}',
			tr: '{\\mathbf tr\\;}',
			udH: '{\\underline H}',
			refX: '{\\mathbf X}',
			Jac: '{\\overline{J}}',
			spatx: '{\\mathbf x}',
			ani: '{\\overline a}',
			mat: '{\\left[\\begin{array}}',
			tam: '{\\end{array}\\right]}',
			arr: ['\\left.\\begin{array}{#1}', 1],
			rra: '\\end{array}\\right\\}',
			arl: '\\left\{\\begin{array}',
			lra: '\\end{array}\\right.',
			ar: '\\begin{array}',
			ra: '\\end{array}',
			const: '{\\mbox{ const.}}',
			eps: '{\\; \\epsilon}',
			sig: '{\\; \\sigma}',
			th: '{\\theta}',
			sgn: '{\\mbox{sgn}}',
			qed: '{\\; Q.E.D.\\\\}',
			ranqe: '{\\end{eqnarray}}',
			ol: '{\\overline}',
			ul: '{\\underline}',
			bB: '{\\mathbf B}',
			bD: '{\\mathbf D}',
			bE: '{\\mathbf E}',
			bF: '{\\mathbf F}',
			bK: '{\\mathbf K}',
			bS: '{\\mathbf S}',
			bT: '{\\mathbf T}',
			bsig: '{\b\mathf \\sigma}'
		}
	}
});
